### ISSUE TITLE
Package is not workable for stock

### ISSUE THREAD

**Issue by allencccheng** [NickLin910221/Shioaji_Realtime_Kline#1]
I try use this package
it is workable on Futures, but is not workable on Stocks

Error Msg:
Response Code: 200 | Event Code: 16 | Info: TIC/v1/STK/*/TSE/2330 | Event: Subscribe or Unsubscribe ok

AttributeErrorTraceback (most recent call last)
<ipython-input-4-f5638b0a1717> in <module>
     12 
     13 #while True:
---> 14 MXFR1_1K = Contracts.kbars(api.Contracts.Stocks.TSE.TSE2330, "1min")
     15 df = pd.DataFrame({**MXFR1_1K })
     16 df.ts = pd.to_datetime(df.ts)

/opt/conda/lib/python3.8/site-packages/shioaji_realtime_kbars/shioaji_realtime_kbars.py in kbars(self, contract, period)
    101         if contract.__class__ is sj.contracts.Stock:
    102             for _contract_ in self.stk_Contracts:
--> 103                 if contract.contract.code == _contract_.contract.code: return _contract_.getklines(period)
    104             return Kbars(ts = [], Open = [], High = [], Low = [], Close = [], Volume = [], Amount = [])
    105         elif contract.__class__ is sj.contracts.Future or contract.__class__ is sj.contracts.Option:

AttributeError: 'Stock' object has no attribute 'contract'

**Comment by NickLin910221** [comment]
Release v1.0.3 have fixed the problem.
If you have any problems.
Welcome to open the issue to feedback.
