### ISSUE TITLE
Can't get realtime quots of api.Contracts.Indexs.TSE.TSE001

### ISSUE THREAD

**Issue by ftlin08** [NickLin910221/Shioaji_Realtime_Kline#2]
Hello, 
  I subscribe to TSE001 using the following code and get no data. Could you help me? Thanks in advance.

     Contracts.subscribe(api.Contracts.Indexs.TSE.TSE001, last_days = 1, cb = [[strategy1, "1min"]])
    @api.on_tick_stk_v1()
    def callback(exchange: Exchange, tick : TickSTKv1):
        Contracts.update(tick, "stk")

**Comment by NickLin910221** [comment]
Hi,

This package still not support for exclude Stock/Future/Option symbol.
If I have a chance, I'll try to research and arrange for compatibility.

Thanks for advice.
